n=input('Digite algo')
print('Só tem espaço?',n.isspace())
print('É um número?',n.isnumeric())
print('É alfabético?',n.isalpha())
print('É alfabético e um número?',n.isalnum())
print('Está em maiúculas?',n.isupper())
print('Está em minúsculas',n.islower())
print('Está catalizado?',n.isidentifier())
