nom=str(input('Nome completo: '))
nomM=nom.upper()
nomm=nom.lower()
nomq=len(nom.strip())
div=nom.split()
qlnompri=len(div[0])
print('O nome {} com todas as letras maiúsculas é, {}'.format(nom,nomM))
print('O nome {} com todas as letras minúsculas é ,{}'.format(nom,nomm))
print('A quantidade de letras do nome {} é, {}'.format(nom,nomq))
print('A quantidade de letras do primeiro nome é {}'.format(qlnompri))
